version: 2

jobs:
  build:
    working_directory: /go/src/github.com/pingcap/tikv
    docker:
      - image: andelf/pingcap-build:0.1.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - tikv-{{ checksum "Cargo.lock" }}
            - tikv- # used if checksum fails
      - run:
          name: "Github Fixture"
          command: sed -i 's/github/git-non-exist-hub/g' ~/.gitconfig

      - run:
          name: "Format Check"
          command: find . -iname '*.rs' | xargs cargo fmt -- --write-mode overwrite

      - run:
          name: "Build"
          command: cargo build --features "grpcio/link-sys"

      - run:
          name: "Build Tests"
          command: cargo test --features "grpcio/link-sys" --no-run

      - save_cache:
          key: tikv-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - ~/.cargo/git
            - ~/.cargo/registry

      - run:
          name: "Test"
          command: cargo test --features "grpcio/link-sys"
