version: 2

jobs:
  build:
    docker:
      - image: andelf/circleci-build:0.1.6
    working_directory: /go/src/github.com/pingcap/tikv
    steps:
      - checkout
      - restore_cache:
          keys:
            - tikv-{{ checksum "Cargo.lock" }}
            - tikv- # used if checksum fails
      - run:
          name: "Github Fixture"
          command: sed -i 's/github/git-non-exist-hub/g' ~/.gitconfig

      - run:
          name: "Format Check"
          command: find . -iname '*.rs' | xargs cargo fmt -- --write-mode overwrite

      - run:
          name: "Build"
          command: cargo build --features "grpcio/link-sys"

      - run:
          name: "Test Build"
          command: cargo test --features "grpcio/link-sys" --no-run -- --nocapture

      - save_cache:
          key: tikv-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - ~/.cargo/git
            - ~/.cargo/registry

  test:
    docker:
      - image: andelf/circleci-build:0.1.6
    working_directory: /go/src/github.com/pingcap/tikv
    steps:
      - run:
          name: "Test"
          command: cargo test --features "grpcio/link-sys" -- --nocapture

      - run:
          name: "Bench"
          command: cargo test --features "grpcio/link-sys" --bench benches -- --nocapture


workflows:
  version: 2
  default-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
