version: 2

jobs:
  build:
    docker:
      - image: andelf/circleci-build:0.1.4
    working_directory: /go/src/github.com/pingcap/tikv
    steps:
      - checkout
      - run:
          name: "Github Fixture"
          command: sed -i 's/github/git-non-exist-hub/g' ~/.gitconfig

      - run:
          name: "Build"
          command: cargo build --features "grpc/link-sys"

      - run:
          name: "Test"
          command: cargo test --features "grpc/link-sys" -- --nocapture

      - run:
          name: "Bench"
          command: cargo test --features "grpc/link-sys" --bench benches -- --nocapture
