version: 2

jobs:
  build:
    working_directory: /go/src/github.com/pingcap/tikv
    docker:
      - image: andelf/circleci-build:0.1.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - tikv-{{ checksum "Cargo.lock" }}
            - tikv- # used if checksum fails
      - run:
          name: "Github Fixture"
          command: sed -i 's/github/git-non-exist-hub/g' ~/.gitconfig

      - run:
          name: "Format Check"
          command: find . -iname '*.rs' | xargs cargo fmt -- --write-mode overwrite

      - run:
          name: "Build"
          command: cargo build --features "grpcio/link-sys"

      - run:
          name: "Build Tests"
          command: >
            cargo test --features "grpcio/link-sys" --no-run --all --message-format=json |
              jq -r 'select(.profile.test) | .filenames[]' |
              tee test.filenames

      - save_cache:
          key: tikv-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - ~/.cargo/git
            - ~/.cargo/registry

      - run:
          name: "Save Workspace"
          command: |
            mkdir -p ./out/tests
            for f in $(cat test.filenames); do
              cp -i $f ./out/tests/
            done

      - persist_to_workspace:
          root: out
          paths:
            - tests

  test:
    working_directory: /go/src/github.com/pingcap/tikv
    docker:
      - image: andelf/circleci-build:0.1.6
    steps:
      - attach_workspace:
          at: ~/out
      - run:
          name: "Test"
          command: find ~/out -type f -perm +111 -exec {} \;

workflows:
  version: 2
  default-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
